version: '3'

services:
        postges:
                image: nginx
                volumes:
                       - myvolume2:/home/akash
                networks:
                       - nginx1


        mongo:
                image: nginx
                volumes:
                       - myvolume2:/home/akash
                networks:
                       - nginx1


        minio:
                image: nginx
                volumes:
                       - myvolume2:/home/akash
                networks:
                       - nginx1
                expose: 
                        - "8090"
networks:
        nginx1:

volumes:
        myvolume2:        
