version: '3'

services:
        db:
                container_name: dockerpostgres
                image: postgres
                environment: 
                        POSTGRES_PASSWORD: postgres
                        POSTGRES_USER: postgres
                        POSTGRES_DB: slack
                volumes:
                        - ./pgdata:/var/lib/postgresql/data
                networks:
                       - nginx1


        mongo:
                 container_name: dockermongo
                 image: mongo
                 environment:
                         MONGO_INITDB_ROOT_USERNAME: root
                         MONGO_INITDB_ROOT_PASSWORD: example
                 volumes:
                         - ./mongodata:/data/db
                 networks:
                         - nginx1

        minio:
                container_name: dockermino
                image: minio
                environment:
                        minioadmin: minioadmin
                volumes:
                        - ./minodata:/data
                networks:
                        - nginx1
                ports:
                        - "9000:9000"
networks:
        nginx1:
   
