version: '3'

services:
        db:
                container_name: dockerpostgres
                image: postgres
                restart: always
                environment: 
                        POSTGRES_PASSWORD: postgres
                        POSTGRES_USER: postgres
                        
                volumes:
                        - ./pgdata:/var/lib/postgresql/data
                ports:
                        - 3307:3307
                


        adminer:
                 container_name: dockeradminer
                 image: adminer
                 restart: always
                 ports:
                         - 8080:8080

   

   
