version: '3'

services:
        db:
                container_name: dockerpostgres
                image: postgres
                restart: always
                environment: 
                        POSTGRES_PASSWORD: postgres
                        POSTGRES_USER: postgres
                        POSTGRES_DB: slack
                volumes:
                        - ./pgdata:/var/lib/postgresql/data
                ports:
                        - 3307:3307
                networks:
                       - nginx1


        adminar_container:
                 container_name: dockeradminar
                 image: adminer
                 restart: always
                 ports:
                         - 8080:8080

   
networks:
        nginx1:
   
